"""TC-M7-01 〜 TC-M7-09: growth_loop end-to-end orchestrator tests.

Verifies GrowthLoop ties ReflectionCLI + ApproveCLI into one pipeline:
  GapDashboard → ReflectionRunner → staging.yml → ApproveCLI → policy.yml

SRS refs: FR-LOOP-01, FR-LOOP-02.

TDD: tests written BEFORE implementation.
Run: pytest AITuber/tests/test_growth_loop.py
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest

from orchestrator.growth_loop import GrowthLoop, GrowthLoopResult, build_parser

# ── Helpers ────────────────────────────────────────────────────────────────


def _make_gap(intent: str) -> dict:
    return {
        "timestamp": "2026-03-04T10:00:00Z",
        "stream_id": "stream_test",
        "trigger": "avatar_intent_ws",
        "current_state": "reacting",
        "intended_action": {"type": "intent", "name": intent, "param": ""},
        "fallback_used": "nod",
        "context": {"emotion": "happy", "look_target": "camera", "recent_comment": ""},
        "gap_category": "missing_motion",
        "priority_score": 0.0,
    }


def _write_gaps(path: Path, gaps: list[dict]) -> None:
    path.write_text(
        "\n".join(json.dumps(g, ensure_ascii=False) for g in gaps), encoding="utf-8"
    )


_VALID_YAML = """\
```yaml
- intent: loop_gesture
  cmd: avatar_update
  gesture: wave
  priority: 0
  notes: Generated by GrowthLoop test
```
"""


@pytest.fixture
def env(tmp_path: Path):
    """Standard test environment: gaps_dir, policy, staging."""
    gaps_dir = tmp_path / "gaps"
    gaps_dir.mkdir()
    _write_gaps(gaps_dir / "stream.jsonl", [_make_gap("loop_intent")] * 4)
    policy = tmp_path / "bp.yml"
    policy.write_text("", encoding="utf-8")
    staging = tmp_path / "staging.yml"
    return {
        "gaps_dir": gaps_dir,
        "policy": policy,
        "staging": staging,
        "tmp_path": tmp_path,
    }


def _make_loop(env: dict[str, Any], **kwargs) -> GrowthLoop:
    defaults = {
        "gaps_dir": str(env["gaps_dir"]),
        "policy_path": str(env["policy"]),
        "staging_path": str(env["staging"]),
        "top_n": 5,
        "auto_approve": False,
        "auto_reject": False,
        "backend": None,
    }
    defaults.update(kwargs)
    return GrowthLoop(**defaults)


# ── TC-M7-01: no gaps ─────────────────────────────────────────────────────


class TestNoGaps:
    def test_empty_gaps_dir_returns_zero_result(self, tmp_path: Path) -> None:
        """TC-M7-01: gaps なし → GrowthLoopResult(0, 0, 0), 終了コード 0。"""
        empty_dir = tmp_path / "gaps"
        empty_dir.mkdir()
        policy = tmp_path / "bp.yml"
        policy.write_text("", encoding="utf-8")

        loop = GrowthLoop(
            gaps_dir=str(empty_dir),
            policy_path=str(policy),
            staging_path=str(tmp_path / "staging.yml"),
            auto_approve=True,
        )
        result = asyncio.run(loop.run())
        assert result == GrowthLoopResult(0, 0, 0)


# ── TC-M7-02: auto-approve ────────────────────────────────────────────────


class TestAutoApprove:
    def test_auto_approve_approves_all(self, env: dict[str, Any]) -> None:
        """TC-M7-02: mock backend + auto-approve → n_approved > 0。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))

        loop = _make_loop(env, backend=mock_backend, auto_approve=True)
        result = asyncio.run(loop.run())

        assert isinstance(result, GrowthLoopResult)
        assert result.n_generated >= 1
        assert result.n_approved == result.n_generated
        assert result.n_rejected == 0

    def test_policy_updated_after_auto_approve(self, env: dict[str, Any]) -> None:
        """TC-M7-02b: auto-approve 後に policy.yml に内容が追記されている。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))

        loop = _make_loop(env, backend=mock_backend, auto_approve=True)
        asyncio.run(loop.run())

        content = env["policy"].read_text(encoding="utf-8")
        assert "loop_gesture" in content


# ── TC-M7-03: auto-reject ─────────────────────────────────────────────────


class TestAutoReject:
    def test_auto_reject_approves_nothing(self, env: dict[str, Any]) -> None:
        """TC-M7-03: mock backend + auto-reject → n_approved==0, n_rejected>0。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))

        loop = _make_loop(env, backend=mock_backend, auto_reject=True)
        result = asyncio.run(loop.run())

        assert result.n_approved == 0
        assert result.n_generated >= 1
        assert result.n_rejected == result.n_generated

    def test_policy_unchanged_after_auto_reject(self, env: dict[str, Any]) -> None:
        """TC-M7-03b: auto-reject 後に policy.yml が変更されていない。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))
        original = env["policy"].read_text(encoding="utf-8")

        loop = _make_loop(env, backend=mock_backend, auto_reject=True)
        asyncio.run(loop.run())

        assert env["policy"].read_text(encoding="utf-8") == original


# ── TC-M7-04: partial y/n via input_fn ───────────────────────────────────


class TestPartialApproval:
    def test_partial_approval_counts_match(self, env: dict[str, Any]) -> None:
        """TC-M7-04: input_fn が 'n' → n_approved==0, n_rejected==n_generated。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))

        loop = _make_loop(
            env,
            backend=mock_backend,
            input_fn=lambda _: "n",  # reject all
        )
        result = asyncio.run(loop.run())

        assert result.n_approved == 0
        assert result.n_rejected == result.n_generated


# ── TC-M7-05: GrowthLoopResult dataclass ─────────────────────────────────


class TestGrowthLoopResult:
    def test_result_equality(self) -> None:
        """TC-M7-05: GrowthLoopResult フィールド + 等値比較。"""
        r = GrowthLoopResult(n_generated=3, n_approved=2, n_rejected=1)
        assert r.n_generated == 3
        assert r.n_approved == 2
        assert r.n_rejected == 1
        assert r == GrowthLoopResult(3, 2, 1)

    def test_zero_result(self) -> None:
        """TC-M7-05b: GrowthLoopResult(0, 0, 0) はゼロ判定できる。"""
        r = GrowthLoopResult(0, 0, 0)
        assert r.n_generated == 0


# ── TC-M7-06/07: argparser ───────────────────────────────────────────────


class TestParser:
    def test_parser_defaults(self) -> None:
        """TC-M7-06: build_parser() のデフォルト値。"""
        parser = build_parser()
        args = parser.parse_args([])
        assert args.top_n == 5
        assert args.auto_approve is False
        assert args.auto_reject is False

    def test_auto_approve_flag(self) -> None:
        """TC-M7-07: --auto-approve が True になる。"""
        parser = build_parser()
        args = parser.parse_args(["--auto-approve"])
        assert args.auto_approve is True

    def test_auto_reject_flag(self) -> None:
        """TC-M7-07b: --auto-reject が True になる。"""
        parser = build_parser()
        args = parser.parse_args(["--auto-reject"])
        assert args.auto_reject is True


# ── TC-M7-08: staging cleared ────────────────────────────────────────────


class TestStagingCleared:
    def test_staging_cleared_after_loop(self, env: dict[str, Any]) -> None:
        """TC-M7-08: ループ完了後 staging ファイルがクリアされる。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(return_value=(_VALID_YAML, 0.01))

        loop = _make_loop(env, backend=mock_backend, auto_approve=True)
        asyncio.run(loop.run())

        content = env["staging"].read_text(encoding="utf-8").strip()
        assert content == "" or content == "[]" or content == "null"


# ── TC-M7-09: backend exception ──────────────────────────────────────────


class TestBackendException:
    def test_exception_returns_zero_result(self, env: dict[str, Any]) -> None:
        """TC-M7-09: backend 例外 → GrowthLoopResult(0, 0, 0), 終了コード 0。"""
        mock_backend = MagicMock()
        mock_backend.chat = AsyncMock(side_effect=RuntimeError("API error"))

        loop = _make_loop(env, backend=mock_backend, auto_approve=True)
        result = asyncio.run(loop.run())

        assert result == GrowthLoopResult(0, 0, 0)
