"""TC-REFL-09 〜 TC-REFL-15: ProposalValidator unit tests.
TC-REFL-16 〜 TC-REFL-18: PolicyUpdater unit tests.

Maps to: FR-REFL-03, FR-REFL-04.

TDD: these tests were written BEFORE the implementation.
Run: pytest AITuber/tests/test_proposal_validator.py
"""

from __future__ import annotations

import pytest

from orchestrator.policy_updater import PolicyUpdater
from orchestrator.proposal_validator import ProposalValidator, ValidationStatus

# ── Helpers ────────────────────────────────────────────────────────────────


def _valid_entry(**overrides) -> dict:
    base = {
        "intent": "wave_hello",
        "cmd": "avatar_update",
        "gesture": "wave",
        "priority": 0,
        "notes": "Generated by ReflectionRunner",
    }
    base.update(overrides)
    return base


# ── TC-REFL-09: valid entry ────────────────────────────────────────────────


class TestProposalValidatorValid:
    """TC-REFL-09: 有効な BehaviorEntry YAML → VALID (FR-REFL-03)."""

    def test_valid_avatar_update_gesture(self):
        """TC-REFL-09: intent・cmd・gesture が揃っている → VALID。"""
        validator = ProposalValidator()
        result = validator.validate(_valid_entry())

        assert result.status == ValidationStatus.VALID

    def test_valid_avatar_event(self):
        """TC-REFL-09b: avatar_event cmd も VALID。"""
        validator = ProposalValidator()
        entry = {
            "intent": "celebrate_event",
            "cmd": "avatar_event",
            "event": "fireworks",
            "intensity": 1.0,
        }
        result = validator.validate(entry)

        assert result.status == ValidationStatus.VALID

    def test_valid_with_emotion_only(self):
        """TC-REFL-09c: gesture がなくても emotion があれば VALID。"""
        validator = ProposalValidator()
        entry = {"intent": "feel_excited", "cmd": "avatar_update", "emotion": "excited"}
        result = validator.validate(entry)

        assert result.status == ValidationStatus.VALID


# ── TC-REFL-10: missing intent ─────────────────────────────────────────────


class TestProposalValidatorMissingFields:
    """TC-REFL-10〜11: 必須フィールド欠落 → INVALID (FR-REFL-03)."""

    def test_missing_intent(self):
        """TC-REFL-10: intent フィールドなし → INVALID。"""
        validator = ProposalValidator()
        entry = {"cmd": "avatar_update", "gesture": "nod"}
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID
        assert "intent" in result.reason.lower()

    def test_empty_intent(self):
        """TC-REFL-10b: intent が空文字 → INVALID。"""
        validator = ProposalValidator()
        entry = {"intent": "", "cmd": "avatar_update", "gesture": "nod"}
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID

    def test_missing_cmd(self):
        """TC-REFL-11: cmd フィールドなし → INVALID。"""
        validator = ProposalValidator()
        entry = {"intent": "my_action", "gesture": "nod"}
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID
        assert "cmd" in result.reason.lower()

    def test_no_action_fields(self):
        """TC-REFL-11b: gesture / emotion / look_target / event が1つもない → INVALID。"""
        validator = ProposalValidator()
        entry = {"intent": "empty_action", "cmd": "avatar_update"}
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID


# ── TC-REFL-12: cmd not in allowlist ──────────────────────────────────────


class TestProposalValidatorCmdAllowlist:
    """TC-REFL-12: cmd がアローリスト外 → INVALID (FR-REFL-03)."""

    def test_unknown_cmd_rejected(self):
        """TC-REFL-12: cmd = 'exec_shell' → INVALID。"""
        validator = ProposalValidator()
        entry = _valid_entry(cmd="exec_shell")
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID
        assert "cmd" in result.reason.lower()

    @pytest.mark.parametrize("cmd", ["avatar_update", "avatar_event"])
    def test_allowed_cmds_accepted(self, cmd: str):
        """TC-REFL-12b: 許可 cmd は受け入れられる。"""
        validator = ProposalValidator()
        if cmd == "avatar_update":
            entry = _valid_entry(cmd=cmd)
        else:
            entry = {"intent": "test_evt", "cmd": cmd, "event": "sparkle"}
        result = validator.validate(entry)

        assert result.status != ValidationStatus.INVALID or result.reason == ""


# ── TC-REFL-13: blocked words ──────────────────────────────────────────────


class TestProposalValidatorBlockedWords:
    """TC-REFL-13: 危険ワード含む gesture/cmd → INVALID (FR-REFL-03)."""

    @pytest.mark.parametrize(
        "field,value",
        [
            ("gesture", "delete_all"),
            ("gesture", "exec"),
            ("event", "shutdown"),
            ("notes", "rm -rf /"),
        ],
    )
    def test_blocked_word_in_field(self, field: str, value: str):
        """TC-REFL-13: ブロックワードを含むフィールド → INVALID。"""
        validator = ProposalValidator()
        entry = _valid_entry(**{field: value})
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID, (
            f"Expected INVALID for {field}={value!r}, got {result}"
        )


# ── TC-REFL-14: duplicate intent ──────────────────────────────────────────


class TestProposalValidatorDuplicate:
    """TC-REFL-14: 既存ポリシーと重複 intent → DUPLICATE (FR-REFL-03)."""

    def test_duplicate_intent_returns_duplicate(self):
        """TC-REFL-14: 既存ポリシーに同名 intent が存在 → DUPLICATE。"""
        existing = [{"intent": "nod_agreement", "cmd": "avatar_update", "gesture": "nod"}]
        validator = ProposalValidator(existing_policy=existing)
        entry = _valid_entry(intent="nod_agreement")
        result = validator.validate(entry)

        assert result.status == ValidationStatus.DUPLICATE

    def test_no_existing_policy_no_duplicate(self):
        """TC-REFL-14b: 既存ポリシーが空なら DUPLICATE にならない。"""
        validator = ProposalValidator(existing_policy=[])
        entry = _valid_entry(intent="brand_new_action")
        result = validator.validate(entry)

        assert result.status == ValidationStatus.VALID


# ── TC-REFL-15: intent naming convention ──────────────────────────────────


class TestProposalValidatorNaming:
    """TC-REFL-15: intent 名の形式検証 (FR-REFL-03)."""

    def test_intent_with_spaces_rejected(self):
        """TC-REFL-15: intent にスペースを含む → INVALID。"""
        validator = ProposalValidator()
        entry = _valid_entry(intent="my action")
        result = validator.validate(entry)

        assert result.status == ValidationStatus.INVALID

    def test_intent_with_special_chars_rejected(self):
        """TC-REFL-15b: intent に; や & などを含む → INVALID。"""
        validator = ProposalValidator()
        for bad in ["action;drop", "a&b", "x|y"]:
            entry = _valid_entry(intent=bad)
            result = validator.validate(entry)
            assert result.status == ValidationStatus.INVALID, (
                f"Expected INVALID for intent={bad!r}"
            )

    def test_valid_snake_case_intent_accepted(self):
        """TC-REFL-15c: snake_case の intent は VALID。"""
        validator = ProposalValidator()
        entry = _valid_entry(intent="point_at_screen_v2")
        result = validator.validate(entry)

        assert result.status == ValidationStatus.VALID


# ── TC-REFL-16〜18: PolicyUpdater ─────────────────────────────────────────


class TestPolicyUpdater:
    """TC-REFL-16〜18: behavior_policy.yml 追記 (FR-REFL-04)."""

    def test_load_policy_returns_list(self, tmp_path):
        """TC-REFL-16: 既存の YAML を読んで dict リストを返す。"""
        yml = tmp_path / "policy.yml"
        yml.write_text(
            "- intent: nod_agreement\n"
            "  cmd: avatar_update\n"
            "  gesture: nod\n",
            encoding="utf-8",
        )
        updater = PolicyUpdater()
        policy = updater.load_policy(str(yml))

        assert len(policy) >= 1
        assert any(e["intent"] == "nod_agreement" for e in policy)

    def test_load_policy_empty_file_returns_empty_list(self, tmp_path):
        """TC-REFL-16b: 空ファイル → 空リストを返す。"""
        yml = tmp_path / "empty.yml"
        yml.write_text("", encoding="utf-8")
        updater = PolicyUpdater()
        policy = updater.load_policy(str(yml))

        assert policy == []

    def test_append_entries_writes_new_entries(self, tmp_path):
        """TC-REFL-17: 新エントリを YAML ファイル末尾に追記し、追記件数を返す。"""
        yml = tmp_path / "policy.yml"
        yml.write_text(
            "- intent: existing_action\n  cmd: avatar_update\n  gesture: wave\n",
            encoding="utf-8",
        )
        updater = PolicyUpdater()
        new_entries = [
            {
                "intent": "new_action_xyz",
                "cmd": "avatar_update",
                "gesture": "nod",
                "notes": "Added by test",
            }
        ]
        count = updater.append_entries(str(yml), new_entries)

        assert count == 1
        # Re-read the file and verify new entry exists
        policy_after = updater.load_policy(str(yml))
        assert any(e["intent"] == "new_action_xyz" for e in policy_after)
        # Original entry still there
        assert any(e["intent"] == "existing_action" for e in policy_after)

    def test_append_entries_empty_list_returns_zero(self, tmp_path):
        """TC-REFL-18: 空リストを渡した場合 → 0 を返し、ファイルは変更されない。"""
        yml = tmp_path / "policy.yml"
        original = "- intent: stay_action\n  cmd: avatar_update\n  gesture: idle\n"
        yml.write_text(original, encoding="utf-8")
        updater = PolicyUpdater()
        count = updater.append_entries(str(yml), [])

        assert count == 0
        assert yml.read_text(encoding="utf-8") == original

    def test_append_entries_creates_file_if_missing(self, tmp_path):
        """TC-REFL-17b: ファイルが存在しない場合、新規作成して追記する。"""
        yml = tmp_path / "new_policy.yml"
        updater = PolicyUpdater()
        new_entries = [{"intent": "bootstrap_action", "cmd": "avatar_update", "gesture": "wave"}]
        count = updater.append_entries(str(yml), new_entries)

        assert count == 1
        assert yml.exists()
        policy = updater.load_policy(str(yml))
        assert any(e["intent"] == "bootstrap_action" for e in policy)
