"""growth_loop: Phase-2 Growth Loop フル統合オーケストレーター.

Single command to run the full Phase-2 Growth Loop:
  GapDashboard → ReflectionRunner → staging.yml → ApproveCLI → policy.yml

Usage:
    python -m orchestrator.growth_loop [options]
    python -m orchestrator.growth_loop --auto-approve          # CI mode
    python -m orchestrator.growth_loop --top-n 3 --dry-run

SRS refs: FR-LOOP-01, FR-LOOP-02.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from orchestrator.approve_cli import ApproveCLI
from orchestrator.gap_dashboard import _DEFAULT_GAPS_DIR
from orchestrator.llm_modulo_validator import LLMModuloValidator
from orchestrator.policy_updater import PolicyUpdater
from orchestrator.reflection_cli import ReflectionCLI
from orchestrator.scope_config import GrowthScope, ScopeConfig

if TYPE_CHECKING:
    from orchestrator.llm_client import LLMBackend

logger = logging.getLogger(__name__)

_DEFAULT_POLICY = "Assets/StreamingAssets/behavior_policy.yml"
_DEFAULT_STAGING = "proposals_staging.yml"


# ── Result type ────────────────────────────────────────────────────────────


@dataclass
class GrowthLoopResult:
    """Structured result of one Growth Loop execution.

    Attributes
    ----------
    n_generated:  Number of valid proposals generated by the LLM and staged.
    n_approved:   Number of proposals approved and written to behavior_policy.yml.
    n_rejected:   Proposals that were staged but not approved (rejected or skipped).

    FR-LOOP-02
    """

    n_generated: int
    n_approved: int
    n_rejected: int


# ── CLI ────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    """Return the ArgumentParser for growth_loop.

    Flags
    -----
    --gaps-dir   Directory of capability gap JSONL files. (default: Logs/capability_gaps)
    --policy     Path to behavior_policy.yml.
    --staging    Path to proposals staging YAML (temporary file). (default: proposals_staging.yml)
    --top-n      Maximum unique intents to submit to the LLM. (default: 5)
    --auto-approve   Approve all proposals without prompting (CI mode).
    --auto-reject    Reject all proposals (test mode).
    --model      OpenAI model name. (default: gpt-4o-mini)
    """
    p = argparse.ArgumentParser(
        prog="growth_loop",
        description=(
            "Run the full Phase-2 Growth Loop (ReflectionCLI → ApproveCLI) in one command."
        ),
    )
    p.add_argument("--gaps-dir", default=_DEFAULT_GAPS_DIR, metavar="DIR")
    p.add_argument("--policy", default=_DEFAULT_POLICY, metavar="YAML")
    p.add_argument("--staging", default=_DEFAULT_STAGING, metavar="YAML")
    p.add_argument("--top-n", dest="top_n", type=int, default=5, metavar="N")
    p.add_argument(
        "--scope",
        choices=[s.name.lower() for s in GrowthScope],
        default=GrowthScope.YAML_ONLY.name.lower(),
        help="Generation scope (default: yaml_only).",
    )
    p.add_argument(
        "--auto-approve",
        dest="auto_approve",
        action="store_true",
        default=False,
        help="Approve all proposals without prompting (for CI).",
    )
    p.add_argument(
        "--auto-reject",
        dest="auto_reject",
        action="store_true",
        default=False,
        help="Reject all proposals (for testing).",
    )
    p.add_argument("--model", default="gpt-4o-mini")
    return p


# ── Helpers ────────────────────────────────────────────────────────────────


def _count_staging(staging_path: str) -> int:
    """Return the number of proposals in the staging YAML file."""
    path = Path(staging_path)
    if not path.exists():
        return 0
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return 0
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError:
        return 0
    if not isinstance(data, list):
        return 0
    return len(data)


def _count_policy(policy_path: str) -> int:
    """Return the number of entries currently in behavior_policy.yml."""
    return len(PolicyUpdater().load_policy(policy_path))


def _load_staging(staging_path: str) -> list[dict]:
    """Load all proposals from the staging YAML file as a list of dicts."""
    path = Path(staging_path)
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError:
        return []
    if not isinstance(data, list):
        return []
    return [d for d in data if isinstance(d, dict)]


def _clear_staging(staging_path: str) -> None:
    """Remove the staging YAML file if it exists."""
    path = Path(staging_path)
    if path.exists():
        path.unlink()


# ── Core class ─────────────────────────────────────────────────────────────


class GrowthLoop:
    """Orchestrates the full Phase-2 Growth Loop in one object.

    Internally chains:
      ReflectionCLI (--output staging_path)
        → LLMModuloValidator (scope + safety + diff-size gates)
        → ApproveCLI (staging_path)

    Parameters
    ----------
    gaps_dir:      Path to capability gap JSONL directory.
    policy_path:   Path to behavior_policy.yml.
    staging_path:  Temporary staging YAML path (overwritten each run).
    top_n:         Maximum unique intents to submit to the LLM.
    auto_approve:  Approve all staged proposals (CI mode).
    auto_reject:   Reject all staged proposals (test mode).
    input_fn:      Override stdin for interactive y/n. Injected in tests.
    backend:       LLMBackend instance. When None, real OpenAIBackend is used by main().
    scope_config:  Growth scope configuration. Defaults to yaml_only.

    FR-LOOP-01, FR-SCOPE-01, FR-SCOPE-02
    """

    def __init__(
        self,
        gaps_dir: str = _DEFAULT_GAPS_DIR,
        policy_path: str = _DEFAULT_POLICY,
        staging_path: str = _DEFAULT_STAGING,
        top_n: int = 5,
        auto_approve: bool = False,
        auto_reject: bool = False,
        input_fn: Callable[[str], str] | None = None,
        backend: LLMBackend | None = None,
        scope_config: ScopeConfig | None = None,
    ) -> None:
        self.gaps_dir = gaps_dir
        self.policy_path = policy_path
        self.staging_path = staging_path
        self.top_n = top_n
        self.auto_approve = auto_approve
        self.auto_reject = auto_reject
        self.input_fn = input_fn
        self._backend = backend
        self._scope_config: ScopeConfig = (
            scope_config if scope_config is not None else ScopeConfig()
        )

    async def run(self) -> GrowthLoopResult:
        """Execute the full Growth Loop and return structured results.

        Steps:
          1. ReflectionCLI writes valid proposals to staging YAML.
          2. Count staged proposals (n_generated).
          3. Record policy entry count before approval.
          4. ApproveCLI reviews staged proposals, writes approved to policy.
          5. Count new policy entries (n_approved = after − before).

        FR-LOOP-01, FR-LOOP-02
        """
        # ── Step 1: Generate proposals → staging ──────────────────────────
        reflection = ReflectionCLI(
            gaps_dir=self.gaps_dir,
            policy_path=self.policy_path,
            top_n=self.top_n,
            dry_run=False,
            backend=self._backend,
            output_path=self.staging_path,
        )
        await reflection.run()

        # ── Step 2: Count staged proposals ────────────────────────────────
        n_generated = _count_staging(self.staging_path)
        if n_generated == 0:
            logger.info("No proposals staged — Growth Loop complete with no changes.")
            return GrowthLoopResult(0, 0, 0)

        logger.info("Staged %d proposal(s) for review.", n_generated)
        # ── Step 2b: LLMModuloValidator gate (FR-SCOPE-02) ──────────────────
        staged_proposals = _load_staging(self.staging_path)
        lmv = LLMModuloValidator(self._scope_config)
        passed_proposals, lmv_report = lmv.validate(staged_proposals)
        if lmv_report.n_failed > 0:
            logger.info(
                "LLMModuloValidator: %d/%d proposals passed (%d filtered).",
                lmv_report.n_passed,
                lmv_report.n_validated,
                lmv_report.n_failed,
            )
        if not passed_proposals:
            # All proposals were filtered by LLMModuloValidator.
            _clear_staging(self.staging_path)
            return GrowthLoopResult(n_generated, 0, n_generated)

        # Overwrite staging with only the validated proposals.
        Path(self.staging_path).write_text(
            yaml.dump(passed_proposals, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
        # ── Step 3: Snapshot policy before approval ────────────────────────
        policy_before = _count_policy(self.policy_path)

        # ── Step 4: Approve / reject proposals ────────────────────────────
        approve = ApproveCLI(
            staging_path=self.staging_path,
            policy_path=self.policy_path,
            auto_approve=self.auto_approve,
            auto_reject=self.auto_reject,
            input_fn=self.input_fn,
        )
        approve.run()

        # ── Step 5: Compute result ─────────────────────────────────────────
        policy_after = _count_policy(self.policy_path)
        n_approved = max(0, policy_after - policy_before)
        n_rejected = n_generated - n_approved

        result = GrowthLoopResult(
            n_generated=n_generated,
            n_approved=n_approved,
            n_rejected=max(0, n_rejected),
        )
        logger.info(
            "Growth Loop complete: %d generated, %d approved, %d rejected.",
            result.n_generated,
            result.n_approved,
            result.n_rejected,
        )
        return result


# ── main ───────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments, build a real OpenAIBackend, and run the loop."""
    from orchestrator.config import LLMConfig
    from orchestrator.llm_client import OpenAIBackend

    args = build_parser().parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    config = LLMConfig()
    config.model = args.model
    backend = OpenAIBackend(config)
    scope = ScopeConfig(scope=GrowthScope[args.scope.upper()])

    loop = GrowthLoop(
        gaps_dir=args.gaps_dir,
        policy_path=args.policy,
        staging_path=args.staging,
        top_n=args.top_n,
        auto_approve=args.auto_approve,
        auto_reject=args.auto_reject,
        backend=backend,
        scope_config=scope,
    )
    result = asyncio.run(loop.run())
    print(
        f"GrowthLoop: generated={result.n_generated} "
        f"approved={result.n_approved} "
        f"rejected={result.n_rejected}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
