"""PolicyUpdater: read and append entries to behavior_policy.yml.

FR-REFL-04: write validated BehaviorPolicy proposals to the YAML policy file.
The file format matches behavior_policy.yml (flat YAML list, compatible with
the C# BehaviorPolicyLoader parser).
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

# Keys written in this order for each entry (preserves readability)
_KEY_ORDER = [
    "intent", "cmd", "gesture", "emotion", "look_target",
    "event", "intensity", "priority", "notes",
]


def _ordered_entry(entry: dict) -> dict:
    """Return a new dict with known keys in _KEY_ORDER, then any remaining keys."""
    ordered: dict = {}
    for key in _KEY_ORDER:
        if key in entry:
            ordered[key] = entry[key]
    for key, value in entry.items():
        if key not in ordered:
            ordered[key] = value
    return ordered


class PolicyUpdater:
    """Read and append entries to behavior_policy.yml.

    FR-REFL-04
    The YAML file is a top-level list where each element is a BehaviorPolicy entry.
    Compatible with the C# line-based BehaviorPolicyLoader and standard yaml.safe_load.
    """

    # ── Public API ─────────────────────────────────────────────────────────

    def load_policy(self, yml_path: str) -> list[dict]:
        """Parse behavior_policy.yml and return a list of entry dicts.

        FR-REFL-04
        Returns an empty list for an empty or missing file.
        """
        path = Path(yml_path)
        if not path.exists():
            return []

        text = path.read_text(encoding="utf-8").strip()
        if not text:
            return []

        try:
            parsed = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            logger.error("Failed to parse policy YAML at %s: %s", yml_path, exc)
            return []

        if parsed is None:
            return []

        if not isinstance(parsed, list):
            logger.warning("Expected YAML list in %s, got %s", yml_path, type(parsed).__name__)
            return []

        return [e for e in parsed if isinstance(e, dict)]

    def append_entries(self, yml_path: str, entries: list[dict]) -> int:
        """Append validated entries to the YAML policy file.

        FR-REFL-04
        Args:
            yml_path: Path to behavior_policy.yml (created if absent).
            entries:  List of validated BehaviorPolicy entry dicts.
        Returns:
            Number of entries actually written (0 if *entries* is empty).
        """
        if not entries:
            return 0

        path = Path(yml_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        # Ensure existing file ends with a newline before appending
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            if existing and not existing.endswith("\n"):
                existing += "\n"
        else:
            existing = ""

        # If file is empty / fresh, seed with an empty YAML list comment header
        # so the C# parser finds a valid file even before the first entry.
        prefix = ""
        if not existing.strip():
            prefix = (
                "# behavior_policy.yml\n"
                "# Auto-generated by ReflectionRunner (M2).\n"
                "# Manual additions are welcome; see schema at the top of the file.\n\n"
            )

        # Serialise new entries
        ordered_entries = [_ordered_entry(e) for e in entries]
        # yaml.dump produces a YAML list; sort_keys=False preserves our key order
        new_yaml_block = yaml.dump(
            ordered_entries,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
        )

        path.write_text(existing + prefix + new_yaml_block, encoding="utf-8")
        logger.info("PolicyUpdater: appended %d entries to %s", len(entries), yml_path)
        return len(entries)
